#ifndef PHARE_CORE_DEF_PHARE_CONFIG_HPP
#define PHARE_CORE_DEF_PHARE_CONFIG_HPP

#include <string>
#include <unordered_map>

// if __gen_sys.hpp exists, it has been generated by the phare_configurator (config.py)
// if it does not, the build_config() version below reflects that phare_configurator is off
#if __has_include("core/def/_gen_sys.hpp")
#include "core/def/_gen_sys.hpp"
#else

namespace PHARE
{
std::unordered_map<std::string, std::string> build_config()
{
    return {{"PHARE_CONFIG_ERROR", "PHARE NOT BUILT WITH CONFIGURATOR!"}};
}
} // namespace PHARE

#endif

#endif /*PHARE_CORE_DEF_PHARE_CONFIG_HPP*/
