add_subdirectory(minimizing_vector)
add_subdirectory(ndarray)
add_subdirectory(grid)
add_subdirectory(gridlayout)
add_subdirectory(vecfield)
add_subdirectory(particles)
add_subdirectory(ions)
add_subdirectory(electrons)
add_subdirectory(ion_population)
add_subdirectory(maxwellian_particle_initializer)
add_subdirectory(particle_initializer)
add_subdirectory(mhd_state)
