add_subdirectory(alfven_wave)
add_subdirectory(td)
add_subdirectory(translation)
add_subdirectory(tdtagged)
add_subdirectory(shock)
add_subdirectory(dispersion)
add_subdirectory(ionIonBeam)
add_subdirectory(conservation)
add_subdirectory(harris)

add_subdirectory(mhd_alfven2d)
add_subdirectory(mhd_convergence)
add_subdirectory(mhd_multidimensional_convergence)
add_subdirectory(mhd_dispersion)
add_subdirectory(mhd_harris)
add_subdirectory(mhd_harris_3d)
add_subdirectory(mhd_orszagtang)
add_subdirectory(mhd_orszagtang_3d)
add_subdirectory(mhd_rotor)
add_subdirectory(mhd_shock)
