#ifndef PHARE_HDF5_PHARE_HDF5_HPP
#define PHARE_HDF5_PHARE_HDF5_HPP


#if PHARE_HAS_HIGHFIVE

#define _PHARE_WITH_HIGHFIVE(...) __VA_ARGS__
#else
#define _PHARE_WITH_HIGHFIVE(...)
#endif



#endif // PHARE_HDF5_PHARE_HDF5_HPP
