
super: settings

property:
  sys.arch: ${ARCH}

find:
  hdf5:
    inc:
      /usr/include/hdf5/openmpi
      /usr/include/openmpi-${sys.arch}
    lib:
      /usr/lib64/openmpi/lib
      /usr/lib/${sys.arch}-linux-gnu/hdf5/openmpi
