#!/usr/bin/env python3
"""
Generate simulator binding sources in the build directory tree, combining all
permutations into a single python module rather than one module per permutation.

Called from res/cmake/def.cmake when -DGODULE=ON:

    python3 tools/godule.py BUILD_DIR [PERMUTATIONS_FILE]

For each permutation in res/sim/all.txt (or PERMUTATIONS_FILE, i.e.
-DPHARE_PERMUTATIONS), writes BUILD_DIR/godule/cpp_<sim_id>.cpp which template
instantiates that simulator permutation into a submodule, as would otherwise be
done per module via compile definitions in src/python3/CMakeLists.txt. A
generated BUILD_DIR/godule/cpp_sims.cpp declares the python module and
registers each permutation submodule, e.g.

    from pybindlibs import cpp_sims
    cpp_sims.cpp_1_1_2.Simulator

Also writes BUILD_DIR/.godule.cmake, included by def.cmake. def.cmake is processed
before pybind11 and the phare libraries are available, so .godule.cmake defers
module target creation to the end of the top level configure.
"""

import sys
import dataclasses
from pathlib import Path

FILE_DIR = Path(__file__).resolve().parent
ROOT_DIR = FILE_DIR.parent
DEFAULT_PERMUTATIONS = ROOT_DIR / "res" / "sim" / "all.txt"

MODULE_NAME = "cpp_sims"

# matches src/python3/CMakeLists.txt: prefixes applied from the 4th csv token on
TYPE_PREFIXES = (
    "TimeIntegratorType",
    "ReconstructionType",
    "SlopeLimiterType",
    "RiemannSolverType",
)

GENERATED = "// generated by tools/godule.py -- do not edit"

CPP_TEMPLATE = """{generated}

#include "python3/cpp_simulator.hpp"

namespace PHARE::pydata
{{

void declare_{mod_str}(py::module_& parent)
{{
    using namespace PHARE::MHDOpts;
    auto m = parent.def_submodule("{mod_str}");
    declare_sim<SimOpts{{{sim_str}}}>(m);
}}

}} // namespace PHARE::pydata
"""

MODULE_TEMPLATE = """{generated}

#include "pybind11/pybind11.h"

namespace py = pybind11;

namespace PHARE::pydata
{{

{declarations}

PYBIND11_MODULE({module_name}, m)
{{
{registrations}
}}

}} // namespace PHARE::pydata
"""

CMAKE_TEMPLATE = """# generated by tools/godule.py -- do not edit
#
# Included from res/cmake/def.cmake, which is processed before pybind11 and
# the phare libraries exist, so module target creation is deferred to the
# end of the top level configure.

function(godule_add_module)
  pybind11_add_module(@MODULE_NAME@
@SOURCES@
  )
  target_link_libraries(@MODULE_NAME@ PUBLIC phare_simulator)
  target_compile_options(@MODULE_NAME@ PRIVATE
      ${PHARE_WERROR_FLAGS}
      -DPHARE_HAS_HIGHFIVE=${PHARE_HAS_HIGHFIVE}
  )
  set_target_properties(@MODULE_NAME@
      PROPERTIES
      LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/pybindlibs"
  )
  # this is on by default "pybind11_add_module" but can interfere with coverage so we disable it if coverage is enabled
  set_property(TARGET @MODULE_NAME@ PROPERTY INTERPROCEDURAL_OPTIMIZATION ${PHARE_INTERPROCEDURAL_OPTIMIZATION})
  set_property(TARGET @MODULE_NAME@ APPEND_STRING PROPERTY LINK_FLAGS " ${PHARE_LINK_FLAGS}")
endfunction()

cmake_language(DEFER CALL godule_add_module)
"""


@dataclasses.dataclass
class Permutation:
    tokens: list

    @property
    def sim_id(self):  # e.g. 2_1_4_TVDRK3_WENOZ_None_Rusanov_true_false_true
        return "_".join(self.tokens)

    @property
    def mod_str(self):
        return f"cpp_{self.sim_id}"

    @property
    def sim_str(self):  # e.g. 2, 1, 4, TimeIntegratorType::TVDRK3, ...
        typed = list(self.tokens)
        for offset, prefix in enumerate(TYPE_PREFIXES, start=3):
            if len(typed) > offset:
                typed[offset] = f"{prefix}::{typed[offset]}"
        return ", ".join(typed)


def parse_permutations(path):
    perms, seen = [], set()
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        tokens = tuple(bit.strip() for bit in line.split(","))
        if tokens not in seen:
            seen.add(tokens)
            perms.append(Permutation(list(tokens)))
    return perms


def write_if_changed(path, contents):  # preserve mtimes to not trigger rebuilds
    if not path.exists() or path.read_text() != contents:
        path.write_text(contents)


def module_file_contents(perms):
    return MODULE_TEMPLATE.format(
        generated=GENERATED,
        module_name=MODULE_NAME,
        declarations="\n".join(
            f"void declare_{p.mod_str}(py::module_&);" for p in perms
        ),
        registrations="\n".join(f"    declare_{p.mod_str}(m);" for p in perms),
    )


def cmake_file_contents(perms):
    sources = "\n".join(
        f'      "${{CMAKE_BINARY_DIR}}/godule/{name}.cpp"'
        for name in [MODULE_NAME] + [p.mod_str for p in perms]
    )
    return CMAKE_TEMPLATE.replace("@MODULE_NAME@", MODULE_NAME).replace(
        "@SOURCES@", sources
    )


def main():
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    build_dir = sys.argv[1]
    permutations_file = Path(
        sys.argv[2] if len(sys.argv) > 2 and sys.argv[2] else DEFAULT_PERMUTATIONS
    )
    perms = parse_permutations(permutations_file)

    gen_dir = Path(build_dir) / "godule"
    gen_dir.mkdir(parents=True, exist_ok=True)

    for perm in perms:
        write_if_changed(
            gen_dir / f"{perm.mod_str}.cpp",
            CPP_TEMPLATE.format(
                generated=GENERATED, mod_str=perm.mod_str, sim_str=perm.sim_str
            ),
        )
    write_if_changed(gen_dir / f"{MODULE_NAME}.cpp", module_file_contents(perms))

    keep = {f"{name}.cpp" for name in [MODULE_NAME] + [p.mod_str for p in perms]}
    for stale in gen_dir.glob("cpp_*.cpp"):
        if stale.name not in keep:
            stale.unlink()

    write_if_changed(Path(build_dir) / ".godule.cmake", cmake_file_contents(perms))

    print(
        f"godule: {MODULE_NAME} with {len(perms)} permutations from {permutations_file}"
    )


if __name__ == "__main__":
    main()
